### ISSUE TITLE
Data centric configuration

### ISSUE THREAD

**Issue by TanyaChutani** [ClinicalDataScience/autoPETIII#1]
Hi Team,

I was training the data centric model, please let me know if the [configuration](https://github.com/ClinicalDataScience/autoPETIII) is correct or not: 
```
data:
  data_dir: 
  splits_file
  fold: 0
  target_shape: [ 128, 160, 112 ]
  batch_size: 4
  suffix: .nii.gz
  num_workers_train: 0
  num_workers_val: 0

logger:
  experiment: lightning_logs
  name: test_example1

model:
  pretrained: false
  resume: false
  ckpt_path:
  lr: 0.0001
  sw_batch_size: 4
  seed: 42

trainer:
  max_steps: 250000
  check_val_every_n_epoch: 5
  precision: bf16-mixed #32, 16
  accelerator: gpu
  devices: 1
  deterministic: true
  strategy: auto
  sync_batchnorm: true #false

```

Also can we change the batch size or it needs to remain constant?
